name: auto-release

on:
  schedule:
    - cron: "0 8 * * 2"
  workflow_dispatch: {}

permissions:
  actions: read
  contents: write

jobs:
  auto-release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-auto-release.yml@fd699521fc995525d339964a82f6f781581bf471 # 0.57.0
    with:
      release-workflow: create-release.yml
    secrets:
      token: ${{ secrets.REPO_ACCESS }}