name: auto-release

on:
  schedule:
    - cron: "0 8 * * 2"
  workflow_dispatch: {}

permissions:
  actions: read
  contents: write

jobs:
  auto-release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-auto-release.yml@127bf24eda432e06ca81296442031074473d58f4 # 0.55.9
    with:
      release-workflow: create-release.yml
    secrets:
      token: ${{ secrets.REPO_ACCESS }}