name: code-checks

on:
  pull_request: {}
  push:
    branches:
      - "**"

permissions:
  actions: read
  contents: read

jobs:
  gosec:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@203116543badcfcd7abcca662aced7ffcaf438d4 # 0.55.4
    with:
      install-go: true
      lint-commands: |
        make bootstrap-tools
        make lintsec

  golint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@203116543badcfcd7abcca662aced7ffcaf438d4 # 0.55.4
    with:
      install-go: true
      lint-commands: |
        make bootstrap-tools
        make lint
