name: code-checks

on:
  pull_request: {}
  push:
    branches:
      - "**"

permissions:
  actions: read
  contents: read

jobs:
  gosec:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@ec37c041a36a69320d9cb6a4c41c89f84f7e02cd # 0.55.1
    with:
      install-go: true
      lint-commands: |
        make bootstrap-tools
        make lintsec

  golint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@ec37c041a36a69320d9cb6a4c41c89f84f7e02cd # 0.55.1
    with:
      install-go: true
      lint-commands: |
        make bootstrap-tools
        make lint
