name: code-checks

on:
  pull_request: {}
  push:
    branches:
      - "**"

permissions:
  actions: read
  contents: read

jobs:
  gosec:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@5eba4a9063c75ab16cc2c98722ea493f71159331 # 0.53.1
    with:
      install-go: true
      lint-commands: |
        make bootstrap-tools
        make lintsec

  golint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@5eba4a9063c75ab16cc2c98722ea493f71159331 # 0.53.1
    with:
      install-go: true
      lint-commands: |
        make bootstrap-tools
        make lint
