name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-goreleaser.yml@5eba4a9063c75ab16cc2c98722ea493f71159331 # 0.53.1
    with:
      version: ${{ github.event.inputs.version }}
      docker-platforms: linux/amd64,linux/arm64
      docker-tags: |
        ghcr.io/ckotzbauer/sbom-operator:${{ github.event.inputs.version }}
        ghcr.io/ckotzbauer/sbom-operator:latest
      cosign-repository: ghcr.io/ckotzbauer/sbom-operator-metadata
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      ghcr-password: ${{ secrets.GHCR_PASSWORD }}

  job-image-vcn:
    uses: ckotzbauer/sbom-operator/.github/workflows/release-job-image.yml@main
    needs: [release]
    with:
      version: ${{ github.event.inputs.version }}
      job-image: vcn
      docker-platforms: linux/amd64
      docker-tags: |
        ghcr.io/ckotzbauer/sbom-operator/vcn:${{ github.event.inputs.version }}
        ghcr.io/ckotzbauer/sbom-operator/vcn:latest
      cosign-repository: ghcr.io/ckotzbauer/sbom-operator-metadata
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      ghcr-password: ${{ secrets.GHCR_PASSWORD }}
