name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-goreleaser.yml@45d0839af5e9f59dad1371664bd28d2ecf24ff93 # 0.55.5
    with:
      version: ${{ github.event.inputs.version }}
      docker-platforms: linux/amd64,linux/arm64
      docker-tags: |
        ghcr.io/ckotzbauer/sbom-operator:${{ github.event.inputs.version }}
        ghcr.io/ckotzbauer/sbom-operator:latest
      cosign-repository: ghcr.io/ckotzbauer/sbom-operator-metadata
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      ghcr-password: ${{ secrets.GHCR_PASSWORD }}

  job-image-vcn:
    uses: ckotzbauer/sbom-operator/.github/workflows/release-job-image.yml@main
    needs: [release]
    with:
      version: ${{ github.event.inputs.version }}
      job-image: vcn
      docker-platforms: linux/amd64
      docker-tags: |
        ghcr.io/ckotzbauer/sbom-operator/vcn:${{ github.event.inputs.version }}
        ghcr.io/ckotzbauer/sbom-operator/vcn:latest
      cosign-repository: ghcr.io/ckotzbauer/sbom-operator-metadata
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      ghcr-password: ${{ secrets.GHCR_PASSWORD }}

  get-digest:
    needs: [job-image-vcn]
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    steps:
      - name: Setup Crane
        uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # v0.5

      - name: Get image digest
        id: digest
        env:
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
        run: |
          crane auth login ghcr.io -u ${{ github.actor }} -p "${GHCR_PASSWORD}"
          DIGEST=$(crane digest "ghcr.io/ckotzbauer/sbom-operator:${{ github.event.inputs.version }}")
          echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"

  bump-chart:
    needs: [get-digest]
    uses: ckotzbauer/helm-charts/.github/workflows/bump-chart.yaml@main
    with:
      chart: sbom-operator
      app-version: ${{ github.event.inputs.version }}
      image-digest: ${{ needs.get-digest.outputs.digest }}
    secrets: inherit
