name: review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  review:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-review.yml@ec37c041a36a69320d9cb6a4c41c89f84f7e02cd # 0.55.1
    secrets:
      openrouter-token: ${{ secrets.OPENROUTER_TOKEN }}
