name: review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  review:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-review.yml@fd699521fc995525d339964a82f6f781581bf471 # 0.57.0
    secrets:
      openrouter-token: ${{ secrets.OPENROUTER_TOKEN }}
