name: review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  review:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-review.yml@127bf24eda432e06ca81296442031074473d58f4 # 0.55.9
    secrets:
      openrouter-token: ${{ secrets.OPENROUTER_TOKEN }}
