name: scan-grype

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  scan-scan:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-scan.yml@187b42cc2ca9bc9257d6e72bb1c1be730f1d0565 # 0.56.0
    with:
      docker-tag: ghcr.io/ckotzbauer/sbom-operator:latest
