name: scan-grype

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read
  packages: read
  security-events: write

jobs:
  scan-scan:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-scan.yml@127bf24eda432e06ca81296442031074473d58f4 # 0.55.9
    with:
      docker-tag: ghcr.io/ckotzbauer/sbom-operator:latest
