name: test

on:
  pull_request: {}
  push:
    branches:
      - "**"

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  test:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@45d0839af5e9f59dad1371664bd28d2ecf24ff93 # 0.55.5
    with:
      install-go: true
      install-goreleaser: true
      install-cosign: true
      install-syft: true
      build-commands: make build
      test-commands: make test
      report-coverage: true
      coverage-file: cover.out
      build-image: true
      docker-tag: ghcr.io/ckotzbauer/sbom-operator:latest
