name: test

on:
  pull_request: {}
  push:
    branches:
      - "**"

jobs:
  test:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@5eba4a9063c75ab16cc2c98722ea493f71159331 # 0.53.1
    with:
      install-go: true
      install-goreleaser: true
      install-cosign: true
      install-syft: true
      build-commands: make build
      test-commands: make test
      report-coverage: true
      coverage-file: cover.out
      build-image: true
      docker-tag: ghcr.io/ckotzbauer/sbom-operator:latest
